gpu: 'cuda:0'
---
model:
  m1:
    param1 : 1
---
eval:
  type: 'cplx'  # cplx, mag
---
train:
  epoch: 50
  batch_size: 12
  num_workers: 16
  optimizer: 'adam'
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
  frame_num: 128
  fs: 16
  SNR:
    - 0
    - -5
    - -10
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
  type: 'R' # R,C
---
loss:
  type: 'wSDR'
---
scheduler: # Plateau, oneCycle, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
data:
  test_train_ratio: 0.2
  root: '/home/data/'
---
  log:
    root: '/home/nas/user/kbh/'
---
audio:
  frame : 1024
  shift : 256
  sample_rate: 16000

