model:
  m1:
    param1 : 1
---
train:
  epoch: 50
  batch_size: 12
  num_workers: 16
  optimizer: 'adam'
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
  frame_num: 128
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'MSE'
  mwMSELoss : 
    alpha : 0.9
  wSDRLoss :
    alpha : 0.99
---
scheduler: # Plateau, oneCycle, CosineAnnealingLR
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
  CosineAnnealingLR : 
    T_max : 100  # Maximum number of iterations.
    eta_min : 0.000001
---
data:
  clean: ""
  noise: ""
  eval : 
    clean : ""
    noisy : ""
  len_data : 49152 # 4096 * 12
  n_item : 65365
  use_RIR : True
  deverb_clean : False
  clean_rir_len : 0
  RIR_prob : 0.5
  sr : 16000
  SNR : [-5,20]
  target_dB_FS : -15
  target_dB_FS_floating_value :  10
  prob_spk : [0.00, 1.00]
  range_multitalk : [0.2, 0.8]
  residual_clean :
    use : False
    SNR : [20,30]
  spec_augmentation :
    use : False
    time_width : 10
    freq_width : 5
  RandomNoise : 
    use : True
    prob : 0.05
    f_decay : 0.0
  biquad_filter :
    use : True
    prob : 0.1
  remove_dc :
    use : False
    prob : 0.25
  rand_resample : 
    use : True
    prob : 0.1
    r_low : 0.9
    r_high : 1.1
  reverbed_speech_noise :
    use : False
    prob : 0.1
---
  log:
    root: '/home/data/kbh/logs/Default'
    plot_spec : False
    eval : ["PESQ_WB","SISDR","DNSMOS"]
---
audio:
  n_fft : 1024
  n_hop : 256
  sr : 16000

